### ISSUE TITLE
Members of polymorphic states are enumerated redundantly

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#116]
From the result of the following query:
> Generated from the Phenoscape Knowledgebase on 2019-6-8 by Ontotrace query:
> * taxa: <http://purl.obolibrary.org/obo/VTO_0036216>
> * entities: <http://purl.obolibrary.org/obo/UBERON_4200075> or (<http://purl.obolibrary.org/obo/BFO_0000050> some <http://purl.obolibrary.org/obo/UBERON_4200075>)
```xml
      <states id="sbc249710-1266-48de-873a-a931cf39806f">
        <state label="present" id="UBERON_2002002_1" symbol="1"/>
        <state label="absent" id="UBERON_2002002_0" symbol="0"/>
        <polymorphic_state_set id="s3c8b56ee-0c91-42f3-9ef3-595ddeb77f27" symbol="0 and 1">
          <member state="UBERON_2002002_0"/>
          <member state="UBERON_2002002_1"/>
          <member state="UBERON_2002002_0"/>
          <member state="UBERON_2002002_1"/>
        </polymorphic_state_set>
      </states>
```

**Comment by balhoff** [comment]
@Shalsh23 please take a look at this. A good place to start is:

https://github.com/phenoscape/phenoscape-kb-services/blob/ab1c41240b1cd4c7178d5ce08525ad558b559702/src/main/scala/org/phenoscape/kb/PresenceAbsenceOfStructure.scala#L63

**Comment by Shalsh23** [comment]
@hlapp Me and @balhoff haven't been able to replicate this error. Would you be able to specify the exact url that caused it?

**Comment by hlapp** [comment]
Indeed the query I posted doesn't show the redundant enumeration anymore. I don't currently have another example that does still show it, so I'm going to close this.
