### ISSUE TITLE
NeXML returned by API is unnecessarily verbose, and doesn't use prefix convention

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#12]
The NeXML generated by the API (for example the OntoTrace service) necessarily makes extensive use of the NeXML schema, but rather than defining the namespace once at the root element it defines for each and every element for which it's needed.

Also, to make life of the less than perfect XML-parsing clients easier, it should use the `nex` prefix rather than the generic `ns` for the namespace, as per convention. See http://prefix.cc/nex for prefix convention and ropensci/RNeXML#124 for some context.

**Comment by balhoff** [comment]
@hlapp @xu-hong I have cleaned up all the namespace handling for NeXML output. So don't go too far down any workarounds for the current output. I just need to get the updated code deployed, which in this particular case, as part of Phenex, is a little trickier than it ought to be.

**Comment by balhoff** [comment]
Fixed by 93ecbd95da863a03df03092614c238406e58714c and deployed.
