### ISSUE TITLE
Set up utest

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-services#121]
We should have real tests running. There is a script in `test` that can be converted to a utest.

**Comment by Shalsh23** [comment]
Do you mean this - `https://github.com/phenoscape/phenoscape-kb-services/blob/master/src/test/scala/org/phenoscape/kb/MatrixRendererTest.scala` ?

**Comment by Shalsh23** [comment]
> Do you mean this - `https://github.com/phenoscape/phenoscape-kb-services/blob/master/src/test/scala/org/phenoscape/kb/MatrixRendererTest.scala` ?



> We should have real tests running. There is a script in `test` that can be converted to a utest.

Do you mean this - https://github.com/phenoscape/phenoscape-kb-services/blob/master/src/test/scala/org/phenoscape/kb/MatrixRendererTest.scala ?

**Comment by balhoff** [comment]
Yes.
