### ISSUE TITLE
Retain user-submitted term order in dependency service

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-services#127]
@uyedaj suggests returning the matrix ordered the same way the user submits the request, rather than sorted alphabetically.

**Comment by hlapp** [comment]
Note that phenoscape/rphenoscape#90 adds an dependency matrix function to RPhenoscape which optionally preserves order.

So if implementing this on the server side is expensive either in implementation or for performance, it is not necessary for the R interface. (Reordering in R is both easy and very fast.)
