### ISSUE TITLE
Method to obtain taxonomic rank is missing

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#13]
The term detail method doesn't return all annotations for a term (or class), and the classification method doesn't include taxonomic rank either (arguably justifiably so because taxonomic rank only applies to classes that represent taxa).

Tagging @xu-hong as she needs this for building the rphenoscape API.

**Comment by balhoff** [comment]
I had an undocumented taxon info service, although it was missing rank. I added rank information and documented the service at Apiary: http://docs.phenoscapekb.apiary.io/#reference/taxa/taxon-info

How does that look?

**Comment by hlapp** [comment]
Looks great! Two comments:

1. Why not include synonyms? It's essentially a taxon detail call, so shouldn't it return all details?
2. Shouldn't the URL pattern use all slashes rather than a parameter? But I guess that's a minor design detail. Primarily we should stay consistent.

**Comment by balhoff** [comment]
The rank info is deployed now (forgot to push to production earlier). I created issue #22 for synonyms. I don't have strong feelings about URI segments vs parameters. We can review that sometime if you want.
