### ISSUE TITLE
/term/labels fails to return labels for terms for which /term/label does return one

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#139]
Here's an example:
```sh
curl -X GET "https://kb.phenoscape.org/api/term/labels?iris=http%3A%2F%2Fpurl.org%2Fphenoscape%2Fexpression%3Fvalue%3D%253Chttp%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000051%253E%2Bsome%2B%253Chttp%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000465%253E" -H "accept: application/json"
```
yields an empty result, whereas
```sh
curl -X GET "https://kb.phenoscape.org/api/term/label?iri=http%3A%2F%2Fpurl.org%2Fphenoscape%2Fexpression%3Fvalue%3D%253Chttp%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000051%253E%2Bsome%2B%253Chttp%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000465%253E" -H "accept: application/json"
```
yields
```js
{
  "@id": "http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000465%3E",
  "label": "has part some material anatomical entity"
}
```

**Comment by hlapp** [comment]
I have a workaround for this now that takes extra time (because it queries /term/label for labels that /term/labels failed to resolve), but works. So it'd be nice to get this in one API query shot, but RPhenoscape will already give the correct result.

**Comment by balhoff** [comment]
TODO: check whether the plural `labels` service is used. Should we consolidate this to a single service that accepts either a single term or an array?

**Comment by balhoff** [comment]
Also, these should work the same—compute the label for the `labels` service.

**Comment by Shalsh23** [comment]
Discussion update:
Input/output of label(s) methods remains same as it originally was to make sure it is backwards compatible. However, both will use term.labels() implementation in the backend. One of the two will then be phased out in the next version.
