### ISSUE TITLE
Provide methods that make it easier to compute common ancestors

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#14]
This will be particularly useful for taxonomy-based use-cases (see for example ropensci/traits#40). At present the classification API only returns direct subclasses and superclasses. Obtaining the ancestors path to the root thus requires potentially many API queries. 

In addition it would also be really useful to have a common ancestor API method (given a number of class IDs, return the class for which all of the input classes are a subclass).

cc @xu-hong

**Comment by balhoff** [comment]
Do you specifically want to get the path to the root? Or just obtain all the ancestors? I am guessing the former.

And for the second request, I assume you want the *lowest* common ancestor, right?

**Comment by hlapp** [comment]
> I assume you want the _lowest_ common ancestor

Correct.

> path to the root or obtain all the ancestors

Good point - there may be multiple paths to the root. So I think short of preempting what the client wants to do with the result, the right default is to return _all paths to the root_. There should not beamy ancestors that aren't part of one of those paths . There could be a parameter to control whether only the shortest path(s) are desired (though there may still be multiple shortest paths).

**Comment by balhoff** [comment]
New API: all least common ancestors for a list of terms:
http://docs.phenoscapekb.apiary.io/#reference/terms/least-common-subsumers/return-the-set-of-least-common-subsumers-for-a-set-of-terms

**Comment by balhoff** [comment]
@hlapp how do you imagine paths to the root to look in returned data? Nested? Collection of triples? It would be easy to return all the ancestors as a set of `subClassOf` triples, leaving the client to sort out how many different paths are actually possible. In reality for taxonomy there will probably be only one path to the root.

**Comment by hlapp** [comment]
I'm inclined to take the path to the root out of this issue and make it a separate one.

Re: the LCA, because there can well be multiple ones, one piece of information that would be very nice to have is the path distance of an LCA to each of the input terms. I.e., the path distance would either be an array of values in the same order as the input terms, or an array of (term, path distance) tuples.

**Comment by hlapp** [comment]
I should also note that we have found a different, and much more effective method for supporting multiple taxon and entity input terms in rphenoscape, which is using a disjunction class expression. This may make slower querying, but it works well, and it is effective in delegating matrix construction to the API backend. (A common ancestor-based approach would require pruning of the matrix on the client side.)

**Comment by balhoff** [comment]
Oh, I didn't realize that was your goal with this. Disjunction is what I usually do when given a list of taxa for a Phenoscape matrix request.

**Comment by balhoff** [comment]
@hlapp is the paths to root service still desired? If so, could you create an issue for that and close this one if the LCA service meets your needs?

**Comment by hlapp** [comment]
@balhoff - see #23.

**Comment by hlapp** [comment]
@balhoff is the LCA query a slow or inefficient one to answer? @xu-hong uses it currently to determine whether one term is an ancestor or descendant of another. It seems to work well and is straightforward, but if that's an inefficient query on the backend then maybe we should elevate #23 to higher priority.

**Comment by balhoff** [comment]
@hlapp are you asking because it is running slowly for you? Yes, it is somewhat slow (requires 2 SPARQL queries and then some subtraction between the results). Answering whether one term is an ancestor of another should be quick.

**Comment by hlapp** [comment]
Should we then elevate the path query in priority, or are you recommending yet a different (or new) API method?

**Comment by balhoff** [comment]
If speed is an issue, the question of whether one term is an ancestor of another would be faster to answer. Constructing the path to root (rather than returning all ancestors) would require more computation, not a single query.
