### ISSUE TITLE
/study/phenotypes does not include the character?

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#147]
It seems that the result returned by `/study/phenotypes` does not include the character. It seems that the (outer) `@id` value identifies the character state. How would one query which character states had been grouped under the same character by the study author(s).

Would one have to retrieve the study matrix for that, and then match character state IDs to those in the matrix? (Are these even the same?)

The [Semantic Similarity within and between characters](https://github.com/phenoscape/rphenoscape/wiki/User-Stories#semantic-similarity-within-and-between-characters) user story depends on this.

**Comment by balhoff** [comment]
@Shalsh23 could you look into adding the character IRI to the return value here?

**Comment by Shalsh23** [comment]
> @Shalsh23 could you look into adding the character IRI to the return value here?

Yes, I'll take a look.

**Comment by Shalsh23** [comment]
@hlapp Are the character state IDs being used anywhere, or just the labels sufficient for the purpose? We are thinking of not exposing the IDs since they are ephemeral and change with each release of the DB.

**Comment by hlapp** [comment]
Do you mean character ID or character state ID?

**Comment by Shalsh23** [comment]
I am sorry, I mean character IDs.

**Comment by hlapp** [comment]
So with character IDs, I think the question you are really asking is, would to be OK to have character IDs that are unique only within a study (because labels cannot be expected to be unique across studies, and characters with identical labels but from different studies should remain distinguishable).

I would say yes, that's acceptable, although it seems also unnecessarily cumbersome (because now a client who wants to aggregate by character in essence has to construct a unique identifier themselves). Also, it means anywhere that the API returns a character ID, it will necessarily have to return the study ID as well.

If the database already has those unique character IDs, I don't see any harm in exposing them, so long as the documentation says how these are ephemeral, and they don't have any appearance of not being ephemeral. For example, not be HTTP URIs, not be in some kind of URN scheme.

**Comment by balhoff** [comment]
@hlapp the character IDs are URIs. It's not that they're unique only within a study—they are unique in the database. We were just wondering if it made any sense to expose another ephemeral ID given that there may not be much for the user to do with them.

**Comment by hlapp** [comment]
> the character IDs are URIs.

I assume they don't resolve then, though?

> It's not that they're unique only within a study—they are unique in the database.

I would expect that if they're IDs. To clarify, when I said _you are really asking [...], would it be OK to have character IDs that are unique only within a study_, this was re: using labels not only as labels but also as identifier, which was @Shalsh23's earlier question.

> We were just wondering if it made any sense to expose another ephemeral ID given that there may not be much for the user to do with them.

So the primary use cases are aggregating by character, which I explained above, and learning more about a character given its identifier. For the latter, we don't have any endpoints yet, mostly because we don't have user stories that would require and inform this. That doesn't mean there couldn't be one in the future. But then again, even if one were to arise, it'll likely be the case that a client would also have (or could be reasonably expected to have) the study ID in hand, so character label and study ID could then be used as a unique compound character ID. Though, if when a client obtained the character from the KB they could have been given a character ID, however ephemeral, along with it that they could then supply back to the KB for other queries, why not do it.
