### ISSUE TITLE
Ability to query information based on phenotype

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#148]
While the API includes endpoints for query for terms, taxa, genes, and studies based on various filters, the ability to extract information for phenotypes is missing.

Specifically, given a phenotype IRI, need endpoints for obtaining
- [x] the entity term(s)
- [x] the quality term(s)
- [x] the studies that include annotations with the phenotype, ideally including character state and character (otherwise it has to be reverse looked up from the study, which will be more expensive than need be) 
- [x] the taxa that have annotations with the phenotype

The following user stories depend on this:
- [Presence/absence-based dependency](https://github.com/phenoscape/rphenoscape/wiki/User-Stories#presenceabsence-based-dependency) between phenotypes (which would have to mean the dependency of their entities)
- [Mutual exclusivity](https://github.com/phenoscape/rphenoscape/wiki/User-Stories#mutual-exclusivity-of-characters-and-character-states), which would arguably be property of the qualities provided the same entity
- [Factors influencing semantic similarity](https://github.com/phenoscape/rphenoscape/wiki/User-Stories#factors-influencing-semantic-similarity)

**Comment by hlapp** [comment]
The first two in the list (entity and quality terms) are in #174.

**Comment by hlapp** [comment]
Studies and taxa to be enabled by the following:

- Add `phenotype_id` to `/study/query` to obtain studies for a phenotype.

**Comment by balhoff** [comment]
`/study/query` and `/taxon/with_phenotype` have been updated with a `phenotype` parameter.

**Comment by balhoff** [comment]
Last thing needed here: document phenotype info service.
