### ISSUE TITLE
/ontotrace produces NeXML files that fail validation

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#149]
For example, the NeXML file from the following command fails the [NeXML validator](http://www.nexml.org):
```
curl -o ontotrace-result.xml -X GET "https://kb.phenoscape.org/api/ontotrace?taxon=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVTO_0036216%3E&entity=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897%3E%20or%20(%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000050%3E%20some%20%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897%3E)&variable_only=false" -H "accept: application/xml"
``` 
It appears that the first row it fails at is also the first row with a polymorphic state reference.

I can't really spot anything that seems invalid. @rvosa could it be that the validator is broken? @balhoff has anything changed recently in generating the NeXML files?

Unfortunately, I don't have an NeXML file lying around that's recent enough to not suffer from the NCName issue anymore, so I can't check well whether it's the validator that's now complaining about something it didn't use to.

**Comment by balhoff** [comment]
It is still the polymorphism symbols, as has come up before.

**Comment by hlapp** [comment]
The `symbol` attribute for `AbstractState`, which `StandardPolymorphicStateSet` inherits from, is defined as `xs:anySimpleType`, so presumably anything should go, including "1 and 0".

That's in contrast to `StandardState`, which also inherits from `AbstractState` but restricts the `symbol` attribute to [`StandardToken`](http://www.nexml.org/doc/schema-1/characters/standard/#StandardToken).

It seems the validator confuses the `symbol` datatype restrictions?

**Comment by hlapp** [comment]
@rvosa is there an issue tracker where we can post this bug?

**Comment by hlapp** [comment]
Opened as rvosa/bio-phylo#44, and closing issue here, due to lack of response from @rvosa as maintainer of the validator.

**Comment by rvosa** [comment]
Sorry for the slow uptake! If this is about "simple" type validation then that's not actually something that Bio::Phylo is responsible for. The validator does two things:
1. schema validation (i.e. type constraints)
2. a check to make sure the nested ID references are correct
It's only step 2 that Bio::Phylo does so I'm a bit puzzled. Is there anything in the response?
