### ISSUE TITLE
Annotation summary result lacks time zone

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#165]
The `/kb/annotation_summary` endpoint returns, as part of the result, the date of the build. However, the formatted value lacks the timezone.

This is bad when used programmatically, such as in RPhenoscape (see https://github.com/phenoscape/phenoscape-kb-services/issues/161). If the string is parsed without explicitly specifying a timezone, the timezone local to wherever the client program runs is used, which will be wrong for nearly all timezones. However, specifying the timezone would require to determine whether the time is during DST or not, because these are not the same timezone.

It also seems that a timezone was meant to be included, since the value ends in 'Z'?

**Comment by balhoff** [comment]
A trailing Z indicates UTC timezone: https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC)

**Comment by hlapp** [comment]
And the time is indeed in UTC? I.e., the last build started or finished (?) at twenty past noon local time on Sep 4, and not later in the afternoon?

**Comment by balhoff** [comment]
It's really true. The build started just after lunch on September 4. 😛 I agree it doesn't indicate whether it's the start or the finish, but it's meant to just be a marker for when the KB has been rebuilt.
