### ISSUE TITLE
Include isDefinedBy in term info

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#188]
It appears that `isDefinedBy` is not currently included in the output of the term info endpoint (`/term`). This would, however, be quite useful information to have ("from which ontology is this term?", "is this an anatomy / quality / taxon ontology term?"), including for where a term would need to be plugged in for other API endpoints ("entity", "quality", "in_taxon" etc parameters).

Could this be included easily? Also, I don't currently see another way of getting at this information. The term search endpoint does return it, but it (in this case needlessly) requires a text search, and would unnecessarily add another query for each term.

**Comment by balhoff** [comment]
I think it should be straightforward to include this.
