### ISSUE TITLE
/term yields zero byte response for non-VTO taxon terms

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#195]
For example:
```
curl -X GET "https://kb.phenoscape.org/api/term?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCBITaxon_7955" -H "accept: application/json"
```
Perhaps the `/terms` endpoint was never meant to field taxonomy term queries. However, the present behavior has three problems:
* It does respond with a valid JSON record to VTO terms, so some taxonomy terms appear perfectly valid query terms.
* It returns useful information for VTO taxonomy terms that (ironically) is not available through the supposedly designated `/taxon` method, in particular synonyms.
* Returning a 200 status code when the input is considered invalid, or with invalid output for an input considered valid, is a bug.

**Comment by balhoff** [comment]
This seems to have been fixed by #209.

**Comment by hlapp** [comment]
Not in production though?

**Comment by balhoff** [comment]
True.
