### ISSUE TITLE
/term returns zero-byte response for post-composed anatomy terms

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#196]
For example, <http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000050%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0010709%3E> yields a zero byte response (with a 200 status code).

In contrast, `/term/classification` does give a valid JSON response for this term (including a label), so it's not obvious why `/term` info shouldn't or can't.

**Comment by Shalsh23** [comment]
@hlapp The reason `term/` gives a zero byte response is because a `label` for that term does not exist in the KB. `term/classification` gives a label by generating it on the fly. But we phased this out some time ago in case of `term/label(s)` both of which return `null` for the iri you have referenced above. For the sake of consistency, we are thinking of returning `null` for this iri in both `term/` and `term/classification` as well. Let us know what you think.

@balhoff .

**Comment by hlapp** [comment]
> The reason `/term` gives a zero byte response is because a `label` for that term does not exist in the KB.

I'm not sure why no label should mean no term info either. If what I'm most interested in is the label, wouldn't I use `/term/labels`? The reason I call `/term` is at least as much about the other information it returns.

**Comment by hlapp** [comment]
Or did you mean to return NULL for the label in `/term` if there is no pre-defined label for the term? That should be OK I think, just would need to be documented.

**Comment by Shalsh23** [comment]
Yes, I meant returning `NULL` for the label in `term/` if it isn't pre-defined.

**Comment by hlapp** [comment]
I guess that's OK in principle. The idea of removing useful functionality (namely generating human-readable labels for terms that don't have these set a-priori in the database, such as what `/term/classification` does) still strikes me as unfortunate. Why remove a capability that currently exists (in `/term/classification`), instead of moving it to the right place (such as `/term`).

**Comment by balhoff** [comment]
In the new pipeline the computation of term label won't exist. I think we should implement what @Shalsh23 suggests, and then if there are terms we wish had labels, we make it a separate issue to insert labels for those terms ahead of time.

**Comment by hlapp** [comment]
So you don't think there is room for an endpoint `/term/labels` that will return the best possible label, which it either draws from the KB content, or if none is present, tries to compute.

**Comment by balhoff** [comment]
> So you don't think there is room for an endpoint /term/labels that will return the best possible label

The problem is that right now it does this by decoding the term IRI, rather than anything smarter. And I think it will be cleaner not to have those crazy long IRIs.

**Comment by hlapp** [comment]
I agree, but your comment is about the algorithm, not the value and feasibility of such an endpoint capability itself. I.e., going forward, the algorithm being used right now will need to be changed, but presumably a different algorithm that achieves the same capability with reasonable performance could still be constructed.
