### ISSUE TITLE
Querying taxon annotations by upper ontology entity terms incorrectly returns a zero count

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#198]
For example:
```
curl -X GET "https://kb.phenoscape.org/api/taxon/annotations?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000004&total=true" -H "accept: application/json"
```
yields a count of zero.

Ironically, this is not true if historical homologs are included:
```
curl -X GET "https://kb.phenoscape.org/api/taxon/annotations?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000004&historical_homologs=true&total=true" -H "accept: application/json"
```
```JS
{
  "total": 38633
}
```
The same is true for serial homologs (although the returned number is – also ironically – much smaller, 2648 for the above term).

See also #189, which is slightly different (in that an entity term is actually required there).

**Comment by Shalsh23** [comment]
This is probably because the `http://purl.obolibrary.org/obo/BFO_0000004 ` iri used in this query does not exist due to missing `BFO` ontology in the database. Querying for this term using 
```curl -X GET "https://kb.phenoscape.org/api/term?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000004%20" -H "accept: application/json" ```
results in an `internal server error` (which is a different issue - it should probably return a different error?).

On querying using the `uberon` term instead yields a non-zero count.
```
curl -X GET "https://kb.phenoscape.org/api/taxon/annotations?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001062&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 801595
}
```

One potential solution is to specify in the documentation that uberon ontology should be used wherever an `anatomical entity` is needed. Does this sound like a good idea? @hlapp @balhoff

**Comment by balhoff** [comment]
I think it would make sense to put in the documentation that anatomical entities should be a subclass of UBERON 'anatomical entity'. This may change if we expand to plants (could go up to a CARO term instead).

**Comment by hlapp** [comment]
But these terms are returned in the subsumer matrix. If you want to exclude them from count queries then they also can't be returned as a subsumer.

Otherwise, as a client I would somehow need to know for which subsumes I can and for which I cannot get a valid count query.

**Comment by hlapp** [comment]
BTW @Shalsh23 perhaps `/term` throws an error for the BFO term, but it is being returned by various other endpoints, including subsumes, and also `/term/all_ancestors`.

So perhaps from your perspective of looking into the database you may say that the term doesn't exist in the database, but from a client's perspective it absolutely does exist, because the API itself returns it in response to certain queries.

**Comment by balhoff** [comment]
@hlapp thanks for the additional context; for some reason I thought you had just picked a high level term for query purposes (should have asked). We will look more into what the structure is here.

**Comment by hlapp** [comment]
@Shalsh23 The original query still returns a zero count, incorrectly. By closing this issue, did you mean to say that upper level ontology terms are now no longer included in the subsumer matrix? Otherwise I think this issue has to remain open.

**Comment by Shalsh23** [comment]
> @Shalsh23 The original query still returns a zero count, incorrectly. By closing this issue, did you mean to say that upper level ontology terms are now no longer included in the subsumer matrix? Otherwise I think this issue has to remain open.

The PR above should resolve this issue but the KB will need to be rebuilt for that change to take effect. I am reopening the issue until that happens.

**Comment by balhoff** [comment]
Result now:

```bash
curl -X GET "https://kb.phenoscape.org/api/taxon/annotations?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000004&total=true" -H "accept: application/json"
```

```json
{"total":807610}
```
