### ISSUE TITLE
Add identifier annotation to character definitions in output NeXML 

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#20]
The NeXML generated by OntoTrace includes taxon identifier annotations for OTUs using the `dwc:taxonID` metadata attribute. There should also be an identifier annotation for characters (`<char/>` elements in the NeXML).

The metadata attribute should have strong enough semantics that a consumer can extract the annotation and assume that the value found is indeed the entity or other identifier for the character. A candidate term proposed by @balhoff is `IAO:denotes` ([IAO:0000219](http://purl.obolibrary.org/obo/IAO_0000219)), which is a subproperty of `IAO:is about` ([IAO:0000136](http://purl.obolibrary.org/obo/IAO_0000136)) and has the following definition:

> denotes is a primitive, instance-level, relation obtaining between an information content entity and some portion of reality. Denotation is what happens when someone creates an information content entity E in order to specifically refer to something. The only relation between E and the thing is that E can be used to 'pick out' the thing. This relation connects those two together. Freedictionary.com sense 3: To signify directly; refer to specifically

Perhaps this is strong enough. Tagging @jar398, @arlin, and @rvosa in case they have a better suggestion.

**Comment by hlapp** [comment]
This is a prerequisite for xu-hong/rphenoscape#2.

**Comment by balhoff** [comment]
This is implemented and live now.
