### ISSUE TITLE
API method for path(s) of a class to the root

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#23]
The path(s) of ancestors to the root is involved in many semantic similarity metric calculations, and in calculating the least common subsumer (LCS). 

As such, they are pretty important. However, the API does meanwhile provide a method for returning the LCS (see #14), and so the priority should depend on client needs to calculate semantic similarity metrics (such that this would happen client-side rather than server-side).

**Comment by balhoff** [comment]
Closing this, since in the meantime we have added several services for use in semantic similarity calculations, and these are already used by rPhenoscape.

**Comment by hlapp** [comment]
Fair enough.
