### ISSUE TITLE
API to obtain NeXML matrix for studies matching taxon or entity expression

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#24]
To better enable retrieving data from the KB that is suitable for comparative analysis, create an API that accepts (similar to the OntoTrace API) an OWL expression for selecting taxa and one for selecting entities, and that then returns the data matrices (presumably in NeXML format) for matching studies. A study matches if it includes one or more of the selected taxa, and one or more of the selected entities.

Perhaps an optional "strict" interpretation could be that in order to match, studies must not include taxa or entities _not_ selected by the input expressions. (This is the same as requiring to include _only_ taxa and entities that were selected, but different from requiring to include _all_ taxa and entities that were selected - the latter would likely be impossible given that the taxon and entity ontologies encompass much more than any particular study ever would.)

**Comment by balhoff** [comment]
I guess you would want the initial service to return a list of publications. Then another service would return NeXML for a given publication ID.

When returning a NeXML matrix for a publication, how much should it resemble the annotated source file in GitHub? Would it be better to store a mapping so that a link directly to that file could be provided for a given publication ID? The EQ annotation format stored by Phenex would be a challenge to recreate from the database representation. However, the OWL version of the annotation could be instead attached to character states in returned NeXML. Having different types of annotated NeXML files from Phenoscape could certainly be a source of confusion though.

**Comment by hlapp** [comment]
> I guess you would want the initial service to return a list of publications. Then another service would return NeXML for a given publication ID.

That would be fine. Note though that from the perspective of the Rphenoscape use case, the intermediate step of returning a list of publications isn't necessary. I.e., there is currently no use case in Rphenoscape to return to its user a list of matching publications. (One could be constructed, I suppose, for text mining the abstracts or full text of those publications. But that's a hypothetical one right now.)

> When returning a NeXML matrix for a publication, how much should it resemble the annotated source file in GitHub?

What matters for the Rphenoscape-motivated use cases is to get a matrix that is useful for comparative trait analysis, with traits (and states) linked to ontology terms. How exactly it mirrors the NeXML file in the Github repo is unimportant.

I suppose the initial web service that you plan that would return a list of matching publications could include links to the respective matrix digitization on Github. Then if a faithful reproduction of that file is what the user wants, they can retrieve it from there and don't need to query the KB. 

> Would it be better to store a mapping so that a link directly to that file could be provided for a given publication ID?

I'm not sure what you mean by "store a mapping". But perhaps it's what I'm referring to above?

> The EQ annotation format stored by Phenex would be a challenge to recreate from the database representation.

I don't think there's a use case right now that requires that.

> However, the OWL version of the annotation could be instead attached to character states in returned NeXML. 

Yes, you can do that.

An alternative way is synthesizing the matrix. If we stay within a study, we know which phenotype annotations go together into a column - namely the ones attached to the states for the same character. States can decompose into multiple EQ annotations, so what was one column in the original matrix can become several columns in the matrix re-synthesized from its phenotype annotations. But we can group the phenotypes that originated from one column by entity-attribute, can't we?

> Having different types of annotated NeXML files from Phenoscape could certainly be a source of confusion though.

I don't think so, so long as you don't make promises in the documentation that the returned content should somehow be expected to be the same as the files in the Phenex file repo.

**Comment by balhoff** [comment]
If not an intermediate list of publications, how would multiple matching data matrices be returned? I thought we had decided against a "union" matrix.

By "storing a mapping", I did mean storing in the KB a link to where the annotated matrix is in GitHub.

**Comment by hlapp** [comment]
> If not an intermediate list of publications, how would multiple matching data matrices be returned? I thought we had decided against a "union" matrix.

You can put many data matrices into a single NeXML document, and many OTU blocks. Each `<characters/>` element references a specific `<otus/>` element, so which one goes with which can be maintained in NeXML. But indeed I'm not sure whether RNeXML has the capabilities to get the correct `<otus/>` for a given `<characters/>` block out. @cboettig - your thoughts?

**Comment by cboettig** [comment]
theoretically RNeXML can either treat these as separate blocks (via list of data.frames, e.g. `get_characters_list()`) or do the join to combine the blocks (the default behavior of `get_characters`).  The union seemed convenient for the kind of comparative methods stuff I had in mind (I'm not as familiar with most other possible applications), so right now the defaults are geared a bit more that way.  Certainly open to ideas on improving this behavior if necessary.

**Comment by hlapp** [comment]
@cboettig I guess my question was, how do you call `get_taxa()` so that it returns the taxa only for one given data matrix. It doesn't take the data matrix or data matrix identifier as input, does it?

**Comment by cboettig** [comment]
`get_taxa_list()`  Most of the get methods should follow this pattern at the moment, `get_thing()` returns the union, `get_thing_list()` returns a list, one item for each block.  

That might change as I re-write the methods to be a bit more consistent in returning data.frames and in containing more of the attribute values.  e.g. I'm thinking of eliminating `get_taxa_list()` and just having `get_taxa` include a column for `parent_id` with the `otus` id.  An R user that cared about which block the taxa came from would then have more ready access to that data, while the return type would also be more consistent.  Particularly in light of the powerful tools we now have with `dplyr` and `tidyr` I'm really trying to move to consistent use of data.frames as the canonical data structure.

**Comment by hlapp** [comment]
> get_taxa_list() Most of the get methods should follow this pattern at the moment, get_thing() returns the union, get_thing_list() returns a list, one item for each block.

Right, but I don't think there's a clear way to connect items in the list returned by `get_taxa_list()` to items in the list returned by `get_characters_list()`, or is there?

I agree that a more consistent use of data.frames will be helpful.

**Comment by cboettig** [comment]
Right -- they suffer the same problem as `get_taxa()` vs `get_characters()` in that respect.  I think the new approach should address that, hopefully across at least most of the `get_` methods.  (trees possibly being the exception, since they currently return in `phylo` class by default instead of a `data.frame`.  It may make sense to offer both formats in that case, since I think the `phylo` format is relatively lossy relative the NeXML, and obviously the user doesn't want to work with the raw S4 or XML objects).

**Comment by balhoff** [comment]
@hlapp @xu-hong please take a look at the two services described under "Studies":

http://docs.phenoscapekb.apiary.io/#reference/studies

The query service is live. The service to retrieve a data matrix is not yet implemented. Before I mock up a data matrix, are there any special annotations within the data matrix that you're expecting to make use of? E.g. dwc:taxon for the OTUs. Are you planning to make use of semantics for the characters and states?

If you do want to synthesize columns using EQ, then I think we need to talk more about how exactly that would work. While annotated character states from the same character would sometimes/often fall under the same entity + attribute, the reality is frequently more complicated than that.

**Comment by balhoff** [comment]
I wonder if a merged NeXML file for this should contain a single `otus` block, with several different `characters` blocks referencing it. My rational is that taxa may be repeated across `otus` blocks and always have the same metadata, but the characters are all unique. A `characters` block can have only one `matrix`. Would it completely confuse RNeXML for the `matrix` in a `characters` block to not reference all the taxa in the linked `otus` block?

**Comment by hlapp** [comment]
I'm not sure how intelligent RNeXML is when constructing the character matrix. @cboettig? After discussing this all at length with @xu-hong yesterday, we're both agreed though that for now we are better off with sticking with the one-study-per-document design.

The main benefit of returning a single multi-study NeXML document would be performance, and so there's a risk here of attempting premature optimization. BTW, as another likely issue, if you did return multiple studies in a single document, you would have to find a way to include the metadata for each study so it remains resolvable which study-level metadata go with which data matrix. 

RNeXML still has to deal much better with multi-matrix, multi-OTUs blocks NeXML documents, and documents with non-unique OTU and character labels, because it is supposed to be able to deal with _all_ valid NeXML documents. But it's quite reasonable to assume that Rphenoscape only has to deal with data coming back from the Phenoscape KB API, and so the variety we can expect to encounter there becomes much more predictable.

I think I'm at the point where I'd rather devote time to intelligently synthesizing a merged matrix for a single document return.

**Comment by cboettig** [comment]
RNeXML shouldn't care about how the otus are grouped.

Completely agree that RNeXML shouldn't have to assume anything about the
NeXML that's not enforced by the schema itself.  I believe that currently
all methods can handle the case of otus being in either separate blocks or
a single block.

The get_characters() method can handle multiple OTU blocks and will return
otu ids.  It does not make any assumptions such as that all the otus must
be found in one block.  Currently it returns the otu id, but not the otus
block id, which is now available in the table returned by get_taxa() along
with the otu ids, so it's just a join away (see RNeXML issue #136).  Since
I believe NeXML expects all ids to be globally unique. Likewise it should
handle multiple characters blocks, please ping me if it does not.

Currently it does not return the characters block id either, or for that
matter, the row id, cell id, states and state ids etc.  If there's a use
case for these we can build them into the existing get_characters()
method.

> RNeXML still has to deal much better with multi-matrix, multi-OTUs blocks
NeXML documents, and documents with non-unique OTU and character labels,
I think the recent commits address the issues I know about there.  If
there's still work to be done, can you expand on this in either new or the
recently closed issues?

Cheers,
Carl

On Thu, Oct 29, 2015, 6:45 AM Hilmar Lapp <notifications@github.com> wrote:

> I'm not sure how intelligent RNeXML is when constructing the character
> matrix. @cboettig <https://github.com/cboettig>? After discussing this
> all at length with @xu-hong <https://github.com/xu-hong> yesterday, we're
> both agreed though that for now we are better off with sticking with the
> one-study-per-document design.
>
> The main benefit of returning a single multi-study NeXML document would be
> performance, and so there's a risk here of attempting premature
> optimization. BTW, as another likely issue, if you did return multiple
> studies in a single document, you would have to find a way to include the
> metadata for each study so it remains resolvable which study-level metadata
> go with which data matrix.
>
> RNeXML still has to deal much better with multi-matrix, multi-OTUs blocks
> NeXML documents, and documents with non-unique OTU and character labels,
> because it is supposed to be able to deal with *all* valid NeXML
> documents. But it's quite reasonable to assume that Rphenoscape only has to
> deal with data coming back from the Phenoscape KB API, and so the variety
> we can expect to encounter there becomes much more predictable.
>
> I think I'm at the point where I'd rather devote time to intelligently
> synthesizing a merged matrix for a single document return.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phenoscape/phenoscape-kb-services/issues/24#issuecomment-152183223>
> .
>
-- 

http://carlboettiger.info

**Comment by hlapp** [comment]
@balhoff - any update on when the matrix retrieval for study API might come online?

**Comment by balhoff** [comment]
This is in progress. Should be able to finish early next week.

**Comment by balhoff** [comment]
Matrix retrieval for a study is now live. It may need some tweaking. Currently it only includes taxa and states that have been ontology-annotated. It includes a link to the EQ phenotype URI. A human-readable label for the phenotype could be provided but requires a change in the KB.

**Comment by hlapp** [comment]
@balhoff [this API method](http://docs.phenoscapekb.apiary.io/#reference/studies/data-matrix-for-study/return-a-data-matrix-in-nexml-format-containing-the-data-for-a-given-study?console=1) currently results in a 500 internal server error. Any idea why that might be?

**Comment by hlapp** [comment]
I think this has been implemented to a sufficient degree given current use cases.
