### ISSUE TITLE
Rework SPARQL queries to handle relation graphs

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-services#316]
Once we change the KB to include "relation graphs" (see https://github.com/phenoscape/pipeline/issues/125), and remove generated "property classes", we will need to update all SPARQL queries underpinning services which make use of property classes. For example: https://github.com/phenoscape/phenoscape-kb-services/blob/ccef16572608b687f49cbd9c17c581c33e079846/src/main/scala/org/phenoscape/kb/queries/TaxaWithPhenotype.scala#L161-L168

```scala
?p $rdfsSubClassOf/$HasPartSome $q .
```

would become:

```scala
?p $HasPart $q .
```

The "redundant" relation graph would need to be in scope for this part of the SPARQL query.

**Comment by Shalsh23** [comment]
Partial list of kb-services (to be updated) to work with relation graphs:

```
/entity/dependency
/taxon/with_phenotype
/taxon/phenotypes
/gene/eq
/phenotype/nearest_eq (undocumented and not being currently used)
/entity/presence/evidence
```

**Comment by Shalsh23** [comment]
List of the remaining services which need to be checked to see if they need updates or not:

- [ ] term
- [ ] term/search
- [ ] term/search_classes
- [ ] term/label
- [ ] term/labels
- [ ] term/classification
- [ ] term/all_ancestors
- [ ] term/all_descendants
- [ ] term/least_common_subsumers
- [ ] term/property_neighbors/object
- [ ] term/property_neighbors/subject
- [ ] term/resolve_label-expression

- [ ] ontotrace

- [ ] similarity/query
- [ ] similarity/best_matches
- [ ] similarity/best_subsumers
- [ ] similarity/subsumed_annotations
- [ ] similarity/profile_size
- [ ] similarity/corpus_size
- [ ] similarity/ic_disparity
- [ ] similarity/jaccard
- [ ] similarity/matrix
- [ ] similarity/frequency

- [ ] entity/search
- [ ] entity/presence
- [ ] entity/absence
- [ ] entity/absence/evidence
- [ ] entity/homology
- [ ] entity/dependency

- [ ] taxon
- [ ] taxon/with_rank
- [ ] taxon/annotated_taxa_count
- [ ] taxon/newick
- [ ] taxon/group
- [ ] taxon/variation_profile
- [ ] taxon/annotations
- [ ] taxon/annotation/sources

- [ ] gene
- [ ] gene/search
- [ ] gene/affecting_entity_phenotype
- [ ] gene/expressed_within_entity
- [ ] gene/phenotypic_profile
- [ ] gene/expression_profile

- [ ] study/query
- [ ] study/taxa
- [ ] study/phenotypes
- [ ] study/matrix

- [ ] phenotype/info
- [ ] phenotype/query

**Comment by balhoff** [comment]
All of these have been updated and merged. Except for similarity services—we will track those separately.
