### ISSUE TITLE
Non-unique character labels in returned study matrix - aggregate states for same entity?

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#35]
The NeXML matrix returned by the [API method for obtaining the matrix for a study](http://docs.phenoscapekb.apiary.io/#reference/studies/data-matrix-for-study) may contain non-unique labels. While NeXML of course allows this, it deserves some discussion as to what is going on here.

Apparently all the characters returned by the API are _entities_, not the entity-attribute strings that must have been used in the originally published matrix. As an obvious consequence, there will be multiple characters for one and the same entity if the original authors had several (and then differing) entity-attribute pairs for the same entity in their matrix.

In essence, returning columns as entities rather than as the original entity-attribute pairs is what the ontology annotations enable us to do. So I find this intriguing, but as is, this leads to duplicated column labels. While the NeXML format doesn't prohibit that, it will trip up many comparative analyses in some way or another. So if we use the ontology annotations to return characters in the form of entities, why don't we then also aggregate all states under the same entity in a single character? I can't see the benefit from having them separated into multiple identically labeled characters, yet this does cause considerable issues downstream.

**Comment by balhoff** [comment]
The characters returned are exactly the same as the ones in the original matrix. So it is just a consequence of how the original data were created. For example, the Fink and Fink matrix linked in the API documentation has character 25 and 26 both as "Ectopterygoid". This matrix may be more prone to this since it was compiled from multiple studies I think.
