### ISSUE TITLE
Empty OTU labels in study matrix returned by API 

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#36]
The NeXML file returned by the [API for obtaining the data matrix for a study](http://docs.phenoscapekb.apiary.io/#reference/studies/data-matrix-for-study) sets the label for a variety of OTUs to an empty string. (As a consequence, OTU labels are then no longer unique, which, although allowed by the NeXML format, causes downstream issues - unnecessarily so, see following.)

However, it's not clear why those would be empty. For example, [the matrix for the study in the API docs example](http://kb.phenoscape.org/api/study/matrix?iri=http://dx.doi.org/10.1111/j.1096-3642.1981.tb01575.x) sets the label as empty for [VTO:0037378](http://purl.obolibrary.org/obo/VTO_0037378), although clearly this taxon does have a non-empty label. And there are other similar examples. So I suspect this is a bug rather than a consequence of what's in the ontology?

**Comment by balhoff** [comment]
This is a consequence of what is in the original data. The matrix taxon has a blank label, but has been annotated with a VTO ID. OTU labels are not always the same as the label for the VTO taxon. In this special case, the VTO taxon label could be applied to the OTU label, but I think instead the source data should just be fixed.

**Comment by balhoff** [comment]
Perhaps open an issue here: https://github.com/phenoscape/phenoscape-data/issues

**Comment by hlapp** [comment]
> This is a consequence of what is in the original data. The matrix taxon has a blank label, but has been annotated with a VTO ID. OTU labels are not always the same as the label for the VTO taxon.

So the OTU label in the original matrix was blank, but a curator thought it was some VTO ID?
 
> In this special case, the VTO taxon label could be applied to the OTU label, but I think instead the source data should just be fixed.

I suggest not to make this more complicated as it is, and to make it most usable. What you're saying suggests that even when the annotated VTO term has a label different from the label the original author used, the label used by the original author (likely an invalid name or deprecated synonym) is returned as OTU label? Which is making the data that much less usable. We have a VTO annotation made by a curator. Why don't we trust it and return its label as the OTU label instead of the original one? At the very least this should be an option in the API, and I'd argue it should actually be the default, with reverting to original labels being an option. (Why would anyone request through an API data that is fraught with taxonomic naming problems, instead of the data that human expert curators have annotated with currently valid names?)

**Comment by hlapp** [comment]
> Perhaps open an issue here: https://github.com/phenoscape/phenoscape-data/issues

I think that'd be a surefire way to ensure nothing happens towards resolving this. We already have everything we need in the database.

**Comment by balhoff** [comment]
I see what you are saying about invalid names and deprecated synonyms. I thought this service was intended to return the original data from the study, with annotations. It is a simple matter to return the VTO label instead.

**Comment by balhoff** [comment]
I've updated the service to use the VTO label. Please reopen if this hasn't addressed the full issue.
