### ISSUE TITLE
/similarity/frequency incorrectly returns zero for "owl:Thing" and corpus taxa

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#380]
`"http://www.w3.org/2002/07/owl#Thing"` is one the subsumers returned in the subsumer matrix, however, when used as input for `/similarity/frequency`, the count returned is zero rather than the corpus size.

This needs to be fixed on the server end. On the client side I shouldn't guess whether zero is somehow the magic number meaning the size of the corpus, or that the occurrence count really is zero.

**Comment by hlapp** [comment]
This currently leads to a test failure in Rphenoscape (phenoscape/rphenoscape#153).

**Comment by hlapp** [comment]
@balhoff what's a reasonable ETA for getting this fixed?

**Comment by balhoff** [comment]
The special semantics of `owl:Thing` can make it tricky to always handle it correctly (and doing so can also be unnecessarily expensive). Would you be okay with the services filtering it out of results? This is likely already done for some services and if so should be made consistent.

**Comment by hlapp** [comment]
Yes I think we can safely filter it out of any semantic similarity-related results, including from the subsumer matrix. It is far from the only upper level term that are commonly in the union for subgraph similarity. (However, this means you should not include it in your own Jaccard calculation, either, or otherwise our scores will start to diverge.)

If someones does pass it into `/similarity/frequency`, it would be better to return "NA" or nothing for the count, rather than zero. I.e., if an IRI gets passed for which you don't have a count, return nothing as the count.

**Comment by hlapp** [comment]
> if an IRI gets passed for which you don't have a count, return nothing as the count, not zero.

Should I post this a separate (generic) issue?

**Comment by balhoff** [comment]
> Should I post this a separate (generic) issue?

That sounds good. I will plan to fix at least this one this week, and see what else needs changing.

**Comment by balhoff** [comment]
We are filtering out owl:Thing from return values: see #383. That should prevent this from being an issue in the future.
