### ISSUE TITLE
Make sorting case-insensitive

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-services#39]
Most of the sorted SPARQL queries are currently case sensitive. This should be corrected everywhere.

**Comment by balhoff** [comment]
Some fixes to this in bddf19fdf6b9a46770acf396a7a7e5ec965b3c69.

**Comment by balhoff** [comment]
@Shalsh23 could you take a broader look at this across different queries that have a SORT BY at the end? We want to make sure that at least in most cases, the sorting is not case sensitive. Example: https://github.com/phenoscape/phenoscape-kb-services/commit/bddf19fdf6b9a46770acf396a7a7e5ec965b3c69

Once you review them we can close this.

**Comment by Shalsh23** [comment]
> @Shalsh23 could you take a broader look at this across different queries that have a SORT BY at the end? We want to make sure that at least in most cases, the sorting is not case sensitive. Example: [bddf19f](https://github.com/phenoscape/phenoscape-kb-services/commit/bddf19fdf6b9a46770acf396a7a7e5ec965b3c69)
> 
> Once you review them we can close this.

I checked for `ORDER BY` in the entire project - looks like all have already been taken care of by you.
