### ISSUE TITLE
matrix for study API endpoint returns result in text/plain, not text/xml

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#41]
The [matrix for study API endpoint](http://docs.phenoscapekb.apiary.io/#reference/studies/data-matrix-for-study/return-a-data-matrix-in-nexml-format-containing-the-data-for-a-given-study?console=1) returns a NeXML file. As expected, the documentation therefore says that the result is returned with `Content-type: text/xml`, but in reality the endpoint returns its results with `Content-type: text/plain`.

**Comment by balhoff** [comment]
Fixed; btw it is `application/xml` (as opposed to `text/xml`).
