### ISSUE TITLE
Web service API documentation at Apiary has gotten out of date

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-services#5]
Not all methods defined in the route are described in Apiary: https://github.com/phenoscape/phenoscape-kb-services/blob/master/src/main/scala/org/phenoscape/kb/Main.scala#L83

**Comment by hlapp** [comment]
I'm increasing this in priority because not knowing what API methods are there makes client development unnecessarily more difficult.

**Comment by hlapp** [comment]
Apiary API documentation has been superseded by Swagger API (OpenAPI) documentation. No longer relevant in the context of Apiary. (However, as it turns out, continues to be relevant for the Swagger API docs.) Closing.
