### ISSUE TITLE
/study/query endpoint fails to process OWL Manchester-format class expressions

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#57]
The documentation expressly allows OWL Manchester class expressions for parameters taxon and entity, and this is required for [one of the documented use cases](https://github.com/xu-hong/rphenoscape#character-matrices-for-studies), which, as shown by the Rmarkdown rendering, worked originally.  (_Note that named entities get converted into `part_of` class expressions. Otherwise the use case would not be that useful._)

When executed with a class expression, the API currently returns a 500 Internal Server Error.

**Comment by balhoff** [comment]
@hlapp I've been looking at adding this back, and initially started the work. But I realized that the reason I made this change was to try making this service more uniform with other services used in data faceting. So at that time I added features including filtering by quality, result size, paging, etc.

The current (but unfortunately not backward compatible) service includes a boolean parameter for including parts. Would you be willing to update the R library to use this parameter?

The supported parameters are:

- entity (IRI) - optional
- quality (IRI) - optional
- in_taxon (IRI) - optional
- publication (IRI) - optional
- parts (bool) - default false
- historical_homologs (bool) - default false
- serial_homologs (bool) - default false
- limit (int) - default 20
- offset (int) - default 0
- total (bool) - default false

I agree that this should not have been changed, and also that we need to keep things stable going forward. But this style allows for much better performance than accepting the open ended expressions. If you can work with this, I will update the API docs to reflect the actually accepted parameters.

**Comment by hlapp** [comment]
I think there are indeed some benefits to switching to this style of faceted API query, for example it's more in tune with how one looks at the data through the UI (at last in the near future), and it doesn't require anyone to be able to understand how to correctly formulate OWL class expressions in Manchester Syntax, which for most comparative methods developers is likely more than they will want to know. In fact, because of this the Rphenoscape code constructs the OWL expression on behalf of the user, so this API would make this unnecessary.

Some questions remain though:
* How would one pass a list of taxa through this API? Right now, it's easy to convert a list of taxa to a corresponding OWL expression and pass that to the API. (I assume this is the `in_taxon` parameter?)
* How would one ask for other relationships than explicitly supported as boolean "include X" parameters? For example, the `develops_from` relationship isn't one of the facets in the list above – presumably that means it's not supported? Perhaps the  API could support `X=true` parameters where if `X` does not match one of the documented parameters, it is taken as a property label (or ID) and then included in the query expression.

The second is lower priority than the first because we have concrete use-cases supporting the first, whereas the latter hasn't come up yet as a query someone wanted to ask.

**Comment by hlapp** [comment]
@balhoff it seems the API endpoint returns incorrect results:

* [_Ictalurus australis_ and "part_of _some_ fin"](http://kb.phenoscape.org/api/study/query?parts=true&taxon=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVTO_0061495&entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&total=true) yields 137 studies.
* [_Ictalurus australis_ and "fin"](http://kb.phenoscape.org/api/study/query?taxon=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVTO_0061495&entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&total=true) yields 93 studies.
* [_Ictalurus australis_](http://kb.phenoscape.org/api/study/query?parts=true&taxon=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVTO_0061495&total=true) yields 191 studies.

The faceted browsing UI shows there is only *one single* study involving _Ictalurus australis_.

**Comment by hlapp** [comment]
OK, so apparently the parameter is now `in_taxon`, not `taxon` (which it used to be). Also, unrecognized parameter names are apparently not flagged as an error (and instead perhaps just silently ignored?). 😒

**Comment by balhoff** [comment]
> OK, so apparently the parameter is now in_taxon, not taxon (which it used to be).

Yes, that's right—as listed above it was updated to match other services. Apologies for the confusion.

> Also, unrecognized parameter names are apparently not flagged as an error (and instead perhaps just silently ignored?). 

Looks like this is true. This hasn't come up before—I can see how it would be useful though. Putting this into Google suggests there are mixed opinions about which is best. I think we should make it an error.

**Comment by hlapp** [comment]
BTW parameters with malformed value result in a 500 error instead of a 400. (I noticed this because R will format 100,000 for the limit in exponential notation, which apparently trips up the server-side code.)

**Comment by hlapp** [comment]
And yes, unrecognized parameters should result in a 400 error with a useful error message.

**Comment by hlapp** [comment]
With phenoscape/rphenoscape#22 rphenoscape implements the new API. Swagger API documentation still needs to be updated, though!

**Comment by balhoff** [comment]
@hlapp when I test bad values for `limit` I get a 400 response. Can you open a separate issue with an example?

**Comment by hlapp** [comment]
Indeed it seems to throw 400 error now.
