### ISSUE TITLE
Charset is not returned in the HTTP response header for Content-Type

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#58]
REST client libraries that need to do conversion of response bodies to string values native to the respective programming language will normally inspect the charset specified in the Content-Type response header, and then use it to perform character encoding conversion as needed. However, the KB API does not return the charset, only the Content-Type itself.

As a result, using Rphenoscape, which uses [`httr::content()`](https://rdrr.io/cran/httr/man/content.html), results in numerous `No encoding supplied: defaulting to UTF-8` warnings, generated by `httr::content()`. We can hardcode the charset when calling this method, however as the documentation says this should only be needed if the web service gives the _wrong_ charset.

I assume this would be easy to fix, and would be useful for _any_ client application.

**Comment by balhoff** [comment]
The API does include `charset` for plain-text responses. As far as I can tell, it would be unusual and perhaps incorrect to include `charset` for a JSON response: http://www.iana.org/assignments/media-types/application/json

The charset is handled automatically by the REST framework, which is pretty strict about which media types have an "open" vs "fixed" charset: https://github.com/akka/akka/issues/17409

If you really want to include it, I think we could hack it in with manual headers, but it doesn't seem correct to me. Would it make sense to use `as = "parsed"` in the R code instead of `as = "text"`?

**Comment by hlapp** [comment]
> The API does include `charset` for plain-text responses. As far as I can tell, it would be unusual and perhaps incorrect to include `charset` for a JSON response: http://www.iana.org/assignments/media-types/application/json

Where did you find that this is unusual? It seems to be fairly common, in fact, if not widespread. For example, Github includes `charset` in all its JSON responses, for example here: https://developer.github.com/v3/#schema

Even Google includes it (the editor of the JSON spec having been a Google employee), for example here (with ETag and related lines removed):

```sh
$ curl -D - -s -o /dev/null https://www.googleapis.com/discovery/v1/apis
HTTP/1.1 200 OK
Vary: Origin
Vary: X-Origin
Content-Type: application/json; charset=UTF-8
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Content-Length: 140399
Server: GSE
Cache-Control: public, max-age=300, must-revalidate, no-transform
Age: 6
Alt-Svc: quic=":443"; ma=2
```

As for including it being possibly incorrect, it seems there are different readings of that: https://stackoverflow.com/a/26206930

Fact of the matter is though that de-facto prominent API providers do include it.

> Would it make sense to use `as = "parsed"` in the R code instead of `as = "text"`?

The documentation for `httr::content()` expressly discourages that for package code (as opposed to ad-hoc application code).

**Comment by hlapp** [comment]
BTW the GO-SPARQL API returns the charset too for `application/json`: https://app.swaggerhub.com/apis/geneontology/gosparql/2.2#/GO%20Causal%20Activity%20Models/get_models

So including it is so common that I have yet to see an official API (aside from the Phenoscape KB) that doesn't do it.

**Comment by hlapp** [comment]
@balhoff I've taken care of this for rphenoscape for now in phenoscape/rphenoscape#27.  It would still be preferable to not have to test for `charset` missing, and for other clients to not be potentially tripped up, but given this fix I am downgrading the priority.

**Comment by balhoff** [comment]
We will close this since it is difficult to modify in akka-http.
