### ISSUE TITLE
Swagger API documentation deployed with wrong basePath

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#590]
The [Swagger docs for the /v2 API](https://kb.phenoscape.org/api/v2/docs/#/) erroneously use `/api/v2-beta` as the basePath. This leads to query errors when trying the API.

BTW the [application.conf example](https://github.com/phenoscape/phenoscape-kb-services/blob/master/src/main/resources/application.conf.example) also has the wrong basePath.

**Comment by balhoff** [comment]
This is fixed now. The example application.conf is just for demonstrating the different fields; it has to be modified for most deployments.
