### ISSUE TITLE
Services for providing supporting states for OntoTrace matrices

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-services#68]
Need two services:

Provide a NeXML file of the ontotrace matrix with supporting states for each inferred state. This is what Jim has been generating for Laura's work.

Provide supporting states for a user-specified inferred state. 
@hlapp

**Comment by wdahdul** [comment]
Evidence for states entailing either presence or absence for a specific entity and taxon is already available (See https://github.com/phenoscape/rphenoscape/issues/34)

**Comment by hlapp** [comment]
@balhoff hasn't this been implemented?

**Comment by balhoff** [comment]
The first part is not available through web services:

> Provide a NeXML file of the ontotrace matrix with supporting states for each inferred state.

The web service provides a file without supporting states.

**Comment by hlapp** [comment]
I think that's OK. Based on the [User Story: Obtaining supporting states](https://github.com/phenoscape/rphenoscape/wiki/User-Stories#obtaining-supporting-states) the stated goal can, I would argue, be achieved _without_ having it all in one matrix (i.e., file).
