### ISSUE TITLE
Include a match indicator field in the search result

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#8]
For the class search API, the returned matches for a text search are ordered by the type of match (exact match to label, contained in label, contained in synonym). The individual result records should include an indicator (in the JSON object) that states the type of match so that a client doesn't have to reconstruct that.

Tagging @xu-hong so she is kept in the loop on updates.

**Comment by balhoff** [comment]
What is the use case for this? Would you like to limit the type of match in the query? E.g. by label, exact synonym, broad synonym

**Comment by hlapp** [comment]
It's more for interpreting the result rather than controlling the match. For example, a client might want to show its users the type of match. Or a client might want to discard matches that aren't of certain types. The latter is Rphenoscape's main use-case for this. Right now, Rphenoscape simply assumes that the first match is a bona-fide match, but this need not be the case.

**Comment by balhoff** [comment]
I am asking because returning this information complicates the query. I try to return a given term only once, while it could have been matched multiple ways. So the match type is flattened out of the SPARQL query before I work with the results. But it doesn't have to be that way. What do you mean by "bona-fide" match? Text match to label vs. synonym?

**Comment by hlapp** [comment]
I think what you're referring to is really a matter of how this field is defined. If the field is defined as _lists **all** reasons due to which the term matches_, then yes this could get complicated. If the field is defined as _the reason the term is included in the matches_, then this reason comes straight off of your processing that you do already. I.e., a perfect label match may also have a partial synonym match, but the reason it's in the result set is the perfect label match.

Does that make sense?

**Comment by balhoff** [comment]
I have added a match type indicator to all the term search APIs.
