### ISSUE TITLE
Typesetting double quotes in API examples

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#93]
Some examples in the Swagger API documentation have "fancy" double quotes rather than straight ASCII <=127 double quotes. This causes an error when submitted to the server, online or through `curl`.

**Comment by hlapp** [comment]
It seems this is a problem with the rendering by Swagger, rather than in the documentation code itself? Apparently, by default the opening and closing double quotes are rendered this way in text that's in the description field. I'm not sure how to suppress that – @balhoff does it support backticks (\`) for enclosing pre-formatted text?

**Comment by balhoff** [comment]
Backticks was the fix, thanks!

**Comment by hlapp** [comment]
@r1t1kg0yal FYI, this should be fixed now.
