### ISSUE TITLE
/similarity/ic_disparity says it takes parameter query_graph but it expects queryGraph 

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#94]
This is quite unfortunate because the other corpus parameter, `corpus_graph` is indeed `corpus_graph`, meaning that although in the documentation the parameters are named consistent, in reality they are not, so it's not simply about fixing the documentation.

I don't really care whether they are `corpus_graph` / `query_graph` or `corpusGraph` / `queryGraph`, they just need to be one way or the other.

**Comment by balhoff** [comment]
I was confused why I had never noticed this; it's because I don't use this service for anything. The disparity is also returned inside `/similarity/best_matches`.
